/*
*  Copyright 2024 MASES s.r.l.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*  http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*
*  Refer to LICENSE for more information.
*/

/*
*  This file is generated by MASES.JNetReflector (ver. 2.5.9.0)
*  using android.jar as reference
*/

using MASES.JCOBridge.C2JBridge;

namespace Javax.Xml.Datatype
{
    #region Duration declaration
    /// <summary>
    /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html"/>
    /// </summary>
    public partial class Duration : MASES.JCOBridge.C2JBridge.JVMBridgeBase<Duration>
    {
        const string _bridgeClassName = "javax.xml.datatype.Duration";
        /// <summary>
        /// Default constructor: even if the corresponding Java class does not have one, it is mandatory for JCOBridge
        /// </summary>
        [global::System.Obsolete("Duration class represents, in .NET, an instance of a JVM interface or abstract class. This public initializer is needed for JCOBridge internal use, other uses can produce unidentible behaviors.")]
        public Duration() { }
        /// <summary>
        /// Generic constructor: it is useful for JCOBridge when there is a derived class which needs to pass arguments to the highest JVMBridgeBase class
        /// </summary>
        [global::System.Obsolete("Duration class represents, in .NET, an instance of a JVM interface or abstract class. This public initializer is needed for JCOBridge internal use, other uses can produce unidentible behaviors.")]
        public Duration(params object[] args) : base(args) { }
    
        private static readonly MASES.JCOBridge.C2JBridge.JVMInterop.IJavaType _LocalBridgeClazz = JVMBridgeBase.ClazzOf(_bridgeClassName);
        private static MASES.JCOBridge.C2JBridge.JVMInterop.IJavaType LocalBridgeClazz => _LocalBridgeClazz ?? throw new global::System.InvalidOperationException($"Class {_bridgeClassName} was not found.");
    
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_BridgeClassName.htm"/>
        /// </summary>
        public override string BridgeClassName => _bridgeClassName;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeAbstract.htm"/>
        /// </summary>
        public override bool IsBridgeAbstract => true;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeCloseable.htm"/>
        /// </summary>
        public override bool IsBridgeCloseable => false;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeInterface.htm"/>
        /// </summary>
        public override bool IsBridgeInterface => false;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeStatic.htm"/>
        /// </summary>
        public override bool IsBridgeStatic => false;
    
        // TODO: complete the class
    
    }
    #endregion

    #region Duration implementation
    public partial class Duration
    {
        #region Constructors
    
        #endregion
    
        #region Class/Interface conversion operators
    
        #endregion
    
        #region Fields
    
        #endregion
    
        #region Static methods
    
        #endregion
    
        #region Instance methods
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#isSet(javax.xml.datatype.DatatypeConstants.Field)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.DatatypeConstants.Field"/></param>
        /// <returns><see cref="bool"/></returns>
        public bool IsSet(Javax.Xml.Datatype.DatatypeConstants.Field arg0)
        {
            return IExecute<bool>("isSet", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#compare(javax.xml.datatype.Duration)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.Duration"/></param>
        /// <returns><see cref="int"/></returns>
        public int Compare(Javax.Xml.Datatype.Duration arg0)
        {
            return IExecute<int>("compare", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getSign()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetSign()
        {
            return IExecute<int>("getSign");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getField(javax.xml.datatype.DatatypeConstants.Field)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.DatatypeConstants.Field"/></param>
        /// <returns><see cref="Java.Lang.Number"/></returns>
        public Java.Lang.Number GetField(Javax.Xml.Datatype.DatatypeConstants.Field arg0)
        {
            return IExecute<Java.Lang.Number>("getField", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#add(javax.xml.datatype.Duration)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.Duration"/></param>
        /// <returns><see cref="Javax.Xml.Datatype.Duration"/></returns>
        public Javax.Xml.Datatype.Duration Add(Javax.Xml.Datatype.Duration arg0)
        {
            return IExecute<Javax.Xml.Datatype.Duration>("add", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#multiply(java.math.BigDecimal)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Math.BigDecimal"/></param>
        /// <returns><see cref="Javax.Xml.Datatype.Duration"/></returns>
        public Javax.Xml.Datatype.Duration Multiply(Java.Math.BigDecimal arg0)
        {
            return IExecute<Javax.Xml.Datatype.Duration>("multiply", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#negate()"/>
        /// </summary>
        /// <returns><see cref="Javax.Xml.Datatype.Duration"/></returns>
        public Javax.Xml.Datatype.Duration Negate()
        {
            return IExecute<Javax.Xml.Datatype.Duration>("negate");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#normalizeWith(java.util.Calendar)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Util.Calendar"/></param>
        /// <returns><see cref="Javax.Xml.Datatype.Duration"/></returns>
        public Javax.Xml.Datatype.Duration NormalizeWith(Java.Util.Calendar arg0)
        {
            return IExecute<Javax.Xml.Datatype.Duration>("normalizeWith", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#addTo(java.util.Calendar)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Util.Calendar"/></param>
        public void AddTo(Java.Util.Calendar arg0)
        {
            IExecute("addTo", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#isLongerThan(javax.xml.datatype.Duration)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.Duration"/></param>
        /// <returns><see cref="bool"/></returns>
        public bool IsLongerThan(Javax.Xml.Datatype.Duration arg0)
        {
            return IExecute<bool>("isLongerThan", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#isShorterThan(javax.xml.datatype.Duration)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.Duration"/></param>
        /// <returns><see cref="bool"/></returns>
        public bool IsShorterThan(Javax.Xml.Datatype.Duration arg0)
        {
            return IExecute<bool>("isShorterThan", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getDays()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetDays()
        {
            return IExecute<int>("getDays");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getHours()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetHours()
        {
            return IExecute<int>("getHours");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getMinutes()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetMinutes()
        {
            return IExecute<int>("getMinutes");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getMonths()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetMonths()
        {
            return IExecute<int>("getMonths");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getSeconds()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetSeconds()
        {
            return IExecute<int>("getSeconds");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getYears()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetYears()
        {
            return IExecute<int>("getYears");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#multiply(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <returns><see cref="Javax.Xml.Datatype.Duration"/></returns>
        public Javax.Xml.Datatype.Duration Multiply(int arg0)
        {
            return IExecute<Javax.Xml.Datatype.Duration>("multiply", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#subtract(javax.xml.datatype.Duration)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.Duration"/></param>
        /// <returns><see cref="Javax.Xml.Datatype.Duration"/></returns>
        public Javax.Xml.Datatype.Duration Subtract(Javax.Xml.Datatype.Duration arg0)
        {
            return IExecute<Javax.Xml.Datatype.Duration>("subtract", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getXMLSchemaType()"/>
        /// </summary>
        /// <returns><see cref="Javax.Xml.Namespace.QName"/></returns>
        public Javax.Xml.Namespace.QName GetXMLSchemaType()
        {
            return IExecute<Javax.Xml.Namespace.QName>("getXMLSchemaType");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getTimeInMillis(java.util.Calendar)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Util.Calendar"/></param>
        /// <returns><see cref="long"/></returns>
        public long GetTimeInMillis(Java.Util.Calendar arg0)
        {
            return IExecute<long>("getTimeInMillis", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#getTimeInMillis(java.util.Date)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Util.Date"/></param>
        /// <returns><see cref="long"/></returns>
        public long GetTimeInMillis(Java.Util.Date arg0)
        {
            return IExecute<long>("getTimeInMillis", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/Duration.html#addTo(java.util.Date)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Util.Date"/></param>
        public void AddTo(Java.Util.Date arg0)
        {
            IExecute("addTo", arg0);
        }
    
        #endregion
    
        #region Nested classes
    
        #endregion
    
        // TODO: complete the class
    }
    #endregion
}