/*
*  Copyright 2024 MASES s.r.l.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*  http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*
*  Refer to LICENSE for more information.
*/

/*
*  This file is generated by MASES.JNetReflector (ver. 2.5.9.0)
*  using android.jar as reference
*/

using MASES.JCOBridge.C2JBridge;

namespace Javax.Xml.Datatype
{
    #region XMLGregorianCalendar declaration
    /// <summary>
    /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html"/>
    /// </summary>
    public partial class XMLGregorianCalendar : Java.Lang.Cloneable
    {
        const string _bridgeClassName = "javax.xml.datatype.XMLGregorianCalendar";
        /// <summary>
        /// Default constructor: even if the corresponding Java class does not have one, it is mandatory for JCOBridge
        /// </summary>
        [global::System.Obsolete("XMLGregorianCalendar class represents, in .NET, an instance of a JVM interface or abstract class. This public initializer is needed for JCOBridge internal use, other uses can produce unidentible behaviors.")]
        public XMLGregorianCalendar() { }
        /// <summary>
        /// Generic constructor: it is useful for JCOBridge when there is a derived class which needs to pass arguments to the highest JVMBridgeBase class
        /// </summary>
        [global::System.Obsolete("XMLGregorianCalendar class represents, in .NET, an instance of a JVM interface or abstract class. This public initializer is needed for JCOBridge internal use, other uses can produce unidentible behaviors.")]
        public XMLGregorianCalendar(params object[] args) : base(args) { }
    
        private static readonly MASES.JCOBridge.C2JBridge.JVMInterop.IJavaType _LocalBridgeClazz = JVMBridgeBase.ClazzOf(_bridgeClassName);
        private static MASES.JCOBridge.C2JBridge.JVMInterop.IJavaType LocalBridgeClazz => _LocalBridgeClazz ?? throw new global::System.InvalidOperationException($"Class {_bridgeClassName} was not found.");
    
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_BridgeClassName.htm"/>
        /// </summary>
        public override string BridgeClassName => _bridgeClassName;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeAbstract.htm"/>
        /// </summary>
        public override bool IsBridgeAbstract => true;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeCloseable.htm"/>
        /// </summary>
        public override bool IsBridgeCloseable => false;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeInterface.htm"/>
        /// </summary>
        public override bool IsBridgeInterface => false;
        /// <summary>
        /// <see href="https://www.jcobridge.com/api-clr/html/P_MASES_JCOBridge_C2JBridge_JVMBridgeBase_IsBridgeStatic.htm"/>
        /// </summary>
        public override bool IsBridgeStatic => false;
    
        // TODO: complete the class
    
    }
    #endregion

    #region XMLGregorianCalendar implementation
    public partial class XMLGregorianCalendar
    {
        #region Constructors
    
        #endregion
    
        #region Class/Interface conversion operators
    
        #endregion
    
        #region Fields
    
        #endregion
    
        #region Static methods
    
        #endregion
    
        #region Instance methods
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#isValid()"/>
        /// </summary>
        /// <returns><see cref="bool"/></returns>
        public bool IsValid()
        {
            return IExecute<bool>("isValid");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#compare(javax.xml.datatype.XMLGregorianCalendar)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.XMLGregorianCalendar"/></param>
        /// <returns><see cref="int"/></returns>
        public int Compare(Javax.Xml.Datatype.XMLGregorianCalendar arg0)
        {
            return IExecute<int>("compare", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getDay()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetDay()
        {
            return IExecute<int>("getDay");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getHour()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetHour()
        {
            return IExecute<int>("getHour");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getMinute()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetMinute()
        {
            return IExecute<int>("getMinute");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getMonth()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetMonth()
        {
            return IExecute<int>("getMonth");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getSecond()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetSecond()
        {
            return IExecute<int>("getSecond");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getTimezone()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetTimezone()
        {
            return IExecute<int>("getTimezone");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getYear()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetYear()
        {
            return IExecute<int>("getYear");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#toXMLFormat()"/>
        /// </summary>
        /// <returns><see cref="Java.Lang.String"/></returns>
        public Java.Lang.String ToXMLFormat()
        {
            return IExecute<Java.Lang.String>("toXMLFormat");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getFractionalSecond()"/>
        /// </summary>
        /// <returns><see cref="Java.Math.BigDecimal"/></returns>
        public Java.Math.BigDecimal GetFractionalSecond()
        {
            return IExecute<Java.Math.BigDecimal>("getFractionalSecond");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getEon()"/>
        /// </summary>
        /// <returns><see cref="Java.Math.BigInteger"/></returns>
        public Java.Math.BigInteger GetEon()
        {
            return IExecute<Java.Math.BigInteger>("getEon");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getEonAndYear()"/>
        /// </summary>
        /// <returns><see cref="Java.Math.BigInteger"/></returns>
        public Java.Math.BigInteger GetEonAndYear()
        {
            return IExecute<Java.Math.BigInteger>("getEonAndYear");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#toGregorianCalendar()"/>
        /// </summary>
        /// <returns><see cref="Java.Util.GregorianCalendar"/></returns>
        public Java.Util.GregorianCalendar ToGregorianCalendar()
        {
            return IExecute<Java.Util.GregorianCalendar>("toGregorianCalendar");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#toGregorianCalendar(java.util.TimeZone,java.util.Locale,javax.xml.datatype.XMLGregorianCalendar)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Util.TimeZone"/></param>
        /// <param name="arg1"><see cref="Java.Util.Locale"/></param>
        /// <param name="arg2"><see cref="Javax.Xml.Datatype.XMLGregorianCalendar"/></param>
        /// <returns><see cref="Java.Util.GregorianCalendar"/></returns>
        public Java.Util.GregorianCalendar ToGregorianCalendar(Java.Util.TimeZone arg0, Java.Util.Locale arg1, Javax.Xml.Datatype.XMLGregorianCalendar arg2)
        {
            return IExecute<Java.Util.GregorianCalendar>("toGregorianCalendar", arg0, arg1, arg2);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getTimeZone(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <returns><see cref="Java.Util.TimeZone"/></returns>
        public Java.Util.TimeZone GetTimeZone(int arg0)
        {
            return IExecute<Java.Util.TimeZone>("getTimeZone", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#normalize()"/>
        /// </summary>
        /// <returns><see cref="Javax.Xml.Datatype.XMLGregorianCalendar"/></returns>
        public Javax.Xml.Datatype.XMLGregorianCalendar Normalize()
        {
            return IExecute<Javax.Xml.Datatype.XMLGregorianCalendar>("normalize");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getXMLSchemaType()"/>
        /// </summary>
        /// <returns><see cref="Javax.Xml.Namespace.QName"/></returns>
        public Javax.Xml.Namespace.QName GetXMLSchemaType()
        {
            return IExecute<Javax.Xml.Namespace.QName>("getXMLSchemaType");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#add(javax.xml.datatype.Duration)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Javax.Xml.Datatype.Duration"/></param>
        public void Add(Javax.Xml.Datatype.Duration arg0)
        {
            IExecute("add", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#clear()"/>
        /// </summary>
        public void Clear()
        {
            IExecute("clear");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#reset()"/>
        /// </summary>
        public void Reset()
        {
            IExecute("reset");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setDay(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        public void SetDay(int arg0)
        {
            IExecute("setDay", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setFractionalSecond(java.math.BigDecimal)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Math.BigDecimal"/></param>
        public void SetFractionalSecond(Java.Math.BigDecimal arg0)
        {
            IExecute("setFractionalSecond", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setHour(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        public void SetHour(int arg0)
        {
            IExecute("setHour", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setMillisecond(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        public void SetMillisecond(int arg0)
        {
            IExecute("setMillisecond", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setMinute(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        public void SetMinute(int arg0)
        {
            IExecute("setMinute", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setMonth(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        public void SetMonth(int arg0)
        {
            IExecute("setMonth", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setSecond(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        public void SetSecond(int arg0)
        {
            IExecute("setSecond", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setTimezone(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        public void SetTimezone(int arg0)
        {
            IExecute("setTimezone", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setYear(int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        public void SetYear(int arg0)
        {
            IExecute("setYear", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setYear(java.math.BigInteger)"/>
        /// </summary>
        /// <param name="arg0"><see cref="Java.Math.BigInteger"/></param>
        public void SetYear(Java.Math.BigInteger arg0)
        {
            IExecute("setYear", arg0);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#getMillisecond()"/>
        /// </summary>
        /// <returns><see cref="int"/></returns>
        public int GetMillisecond()
        {
            return IExecute<int>("getMillisecond");
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setTime(int,int,int,int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <param name="arg1"><see cref="int"/></param>
        /// <param name="arg2"><see cref="int"/></param>
        /// <param name="arg3"><see cref="int"/></param>
        public void SetTime(int arg0, int arg1, int arg2, int arg3)
        {
            IExecute("setTime", arg0, arg1, arg2, arg3);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setTime(int,int,int,java.math.BigDecimal)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <param name="arg1"><see cref="int"/></param>
        /// <param name="arg2"><see cref="int"/></param>
        /// <param name="arg3"><see cref="Java.Math.BigDecimal"/></param>
        public void SetTime(int arg0, int arg1, int arg2, Java.Math.BigDecimal arg3)
        {
            IExecute("setTime", arg0, arg1, arg2, arg3);
        }
        /// <summary>
        /// <see href="https://developer.android.com/reference/javax/xml/datatype/XMLGregorianCalendar.html#setTime(int,int,int)"/>
        /// </summary>
        /// <param name="arg0"><see cref="int"/></param>
        /// <param name="arg1"><see cref="int"/></param>
        /// <param name="arg2"><see cref="int"/></param>
        public void SetTime(int arg0, int arg1, int arg2)
        {
            IExecute("setTime", arg0, arg1, arg2);
        }
    
        #endregion
    
        #region Nested classes
    
        #endregion
    
        // TODO: complete the class
    }
    #endregion
}